"""
Stage -1 — Run identity.

Every pipeline execution (A, B, C, or all three via `run_pipeline.py`) gets
one RUN_ID. Everything *generated* while running the pipeline -- data,
storage, output, and every stage's log file -- is written under
`runs/<run_id>/{data,storage,output,logs}/`, so one directory maps cleanly
onto one S3 prefix when this is deployed.

This module must be imported before `ingestion.setup`, `toc.setup`, or
`book_writer.setup` construct their `PipelinePaths` / `BookPaths` objects,
because it sets the DATA_ROOT / STORAGE_ROOT / OUTPUT_ROOT / LOGS_ROOT env
vars those classes read. Each of those three `setup.py` modules imports this
one first, so whichever pipeline starts up first decides the run for the
whole process -- and since Python only ever executes a module once per
process, running all three pipelines together (`run_pipeline.py`) gives them
the same RUN_ID automatically, with no extra plumbing.

To resume a crashed or partial run (Pipeline C checkpoints after every
section), re-invoke with the same RUN_ID so it lands back in the same
folder:

    RUN_ID=20260806_153000_ab12cd python -m src.run_pipeline_c

Two things are NOT run-scoped, because they are inputs you author, not
output the pipeline generates -- see `ingestion.setup.PipelinePaths.raw_sources`
(SOURCES_ROOT) and `book_writer.setup.BookPaths.constitution` (CONSTITUTION_ROOT).

RUNS_ROOT defaults to ./runs; point it at an S3-mounted path (goofys, s3fs,
an EFS/FSx mount) in deployment and every run's data/storage/output/logs
lands directly in S3, keyed by run id.
"""

import os
import time
import uuid
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()          # reads .env in the cwd (or a parent dir) if present
except ImportError:
    pass                    # python-dotenv is optional; real env vars still work


def _generate_run_id() -> str:
    return f"{time.strftime('%Y%m%d_%H%M%S')}_{uuid.uuid4().hex[:6]}"


# RUN_ID is the one knob you set to resume a specific run; RUNS_ROOT is the
# one knob you set to relocate every run's storage (e.g. onto a mounted S3
# path in deployment). Nothing else about the layout is configurable --
# that's the point: nothing generated by a run can end up scattered outside
# runs/<run_id>/.
RUN_ID = os.environ.setdefault("RUN_ID", _generate_run_id())
RUNS_ROOT = Path(os.getenv("RUNS_ROOT", "./runs"))
RUN_ROOT = RUNS_ROOT / RUN_ID

os.environ["DATA_ROOT"] = str(RUN_ROOT / "data")
os.environ["STORAGE_ROOT"] = str(RUN_ROOT / "storage")
os.environ["OUTPUT_ROOT"] = str(RUN_ROOT / "output")
os.environ["LOGS_ROOT"] = str(RUN_ROOT / "logs")

LOGS_ROOT = Path(os.environ["LOGS_ROOT"])
LOGS_ROOT.mkdir(parents=True, exist_ok=True)
